title: 20170817 Team SⅡ 第48区 291
vod: http://live.snh48.com/Index/invedio/id/291
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20170817/59896ec40cf28bcb9b989d5c.mp4/playlist.m3u8
tags:
- SNH48
- 第48区
thumbnail: 20170817-第48区-09.png
playlists:
- 全部
- 全部公演
- Team SⅡ
- Team SⅡ — 第48区
