title: 20170831 Team XⅡ 代号XⅡ 41
datetime: 2017-08-31T19:15:00+08:00
vod: http://live.snh48.com/Index/invedio/id/301
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20170831/599bd1280cf25ef21dd911eb.mp4/playlist.m3u8
tags:
- SNH48
- 代号XⅡ
thumbnail: 20170831-代号XⅡ-41.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
