title: 20170819 Team HⅡ 美丽世界 27
datetime: 2017-08-19T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/293
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20170819/59896f1b0cf28bcb9b989d5e.mp4/playlist.m3u8
tags:
- SNH48
- 美丽世界
thumbnail: 20170819-美丽世界-27.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
