title: 20171020 Team NⅡ 以爱之名 03
datetime: 2017-10-20T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/364
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171020/59dda0eb0cf2d32740bafa6a.mp4/playlist.m3u8
tags:
- SNH48
- 以爱之名
thumbnail: 20171020-以爱之名-03.png
playlists:
- 全部
- 全部公演
- Team NⅡ
- Team NⅡ — 以爱之名
