title: 20171125 Team XⅡ 代号XⅡ 53
datetime: 2017-11-25T13:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/410
tags:
- SNH48
- 代号XⅡ
- Team XⅡ
- XⅡ
- Team XII
- XII
thumbnail: 20171125-代号XⅡ-53.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
