title: 20171026 Team NⅡ 以爱之名 05
datetime: 2017-10-26T19:15:00+08:00
vod: http://live.snh48.com/Index/invedio/id/373
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171026/59e6c4df0cf23fa04ee4c2fe.mp4/playlist.m3u8
tags:
- SNH48
- 以爱之名
thumbnail: 20171026-以爱之名-05.png
playlists:
- 全部
- 全部公演
- Team NⅡ
- Team NⅡ — 以爱之名
