title: 20171015 Team HⅡ 美丽世界 35
datetime: 2017-10-15T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/357
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171015/59dae2ce0cf2085d7b3feb03.mp4/playlist.m3u8
tags:
- SNH48
- 美丽世界
thumbnail: 20171015-美丽世界-35.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
