title: 20170903 Team HⅡ 美丽世界 30
datetime: 2017-09-03T13:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/305
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20170903/599bd1aa0cf25ef21dd911ef.mp4/playlist.m3u8
tags:
- SNH48
- 美丽世界
thumbnail: 20170903-美丽世界-30.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
