title: 20170920 Team XⅡ 代号XⅡ 45
datetime: 2017-09-20T19:15:00+08:00
vod: http://live.snh48.com/Index/invedio/id/323
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20170920/59b9068e0cf2b9aab1fef918.mp4/playlist.m3u8
tags:
- SNH48
- 代号XⅡ
thumbnail: 20170920-代号XⅡ-45.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
