title: 20170902 Team XⅡ 代号XⅡ 42
datetime: 2017-09-02T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/304
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20170902/599bd1850cf25ef21dd911ee.mp4/playlist.m3u8
tags:
- SNH48
- 代号XⅡ
thumbnail: 20170902-代号XⅡ-42.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
