title: 20170916 Team X 梦想的旗帜 53 杨韫玉生日
datetime: 2017-09-16T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/320
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20170916/59ae59ca0cf2900f3d526a3e.mp4/playlist.m3u8
tags:
- SNH48
- 梦想的旗帜
thumbnail: 20170916-梦想的旗帜-53.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 梦想的旗帜
