title: 20171028 Team X 梦想的旗帜 59
datetime: 2017-10-28T13:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/375
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171028/59e6c5030cf23fa04ee4c2ff.mp4/playlist.m3u8
tags:
- SNH48
- 梦想的旗帜
thumbnail: 20171028-梦想的旗帜-59.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 梦想的旗帜
