title: 20171022 Team HⅡ 美丽世界 37 张昕生日
datetime: 2017-10-22T13:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/369
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171022/59dda14b0cf2d32740bafa6d.mp4/playlist.m3u8
tags:
- SNH48
- 美丽世界
thumbnail: 20171022-美丽世界-37.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
