title: 20171022 Team XⅡ 代号XⅡ 50 潘瑛琪生日
datetime: 2017-10-22T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/371
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171022/59dda16a0cf2d32740bafa6e.mp4/playlist.m3u8
tags:
- SNH48
- 代号XⅡ
thumbnail: 20171022-代号XⅡ-50.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
