title: 20171104 Team X 梦想的旗帜 60 冯晓菲生日
datetime: 2017-11-04T13:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/382
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171104/59ef0c280cf22d4b3516e64a.mp4/playlist.m3u8
tags:
- SNH48
- 梦想的旗帜
thumbnail: 20171104-梦想的旗帜-60.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 梦想的旗帜
