title: 20171008 Team NⅡ 以爱之名 02
datetime: 2017-10-08T13:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/349
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171008/59cdd9fc0cf23bc6a650c14e.mp4/playlist.m3u8
tags:
- SNH48
- 以爱之名
thumbnail: 20171008-以爱之名-02.png
playlists:
- 全部
- 全部公演
- Team NⅡ
- Team NⅡ — 以爱之名
