title: 20170830 Team X 梦想的旗帜 50
datetime: 2017-08-30T19:15:00+08:00
vod: http://live.snh48.com/Index/invedio/id/301
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20170830/599bd1060cf25ef21dd911ea.mp4/playlist.m3u8
tags:
- SNH48
- 梦想的旗帜
thumbnail: 20170830-梦想的旗帜-50.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 梦想的旗帜
