title: 20171110 星梦Mini Live（张怡）
datetime: 2017-11-10T17:25:00+08:00
vod: http://live.snh48.com/Index/invedio/id/393
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171110/5a02da580cf2d7411154dc8e.mp4/playlist.m3u8
tags:
- SNH48
- 星梦Mini Live
- 张怡
thumbnail: 20171110-mini-live-png
playlists:
- 全部
- 音乐
- 星梦Mini Live
- 其它
