title: 20171003 星梦Mini Live（张丹三）
datetime: 2017-10-03T17:25:00+08:00
vod: http://live.snh48.com/Index/invedio/id/339
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171003/59cc81000cf25ea09bb3d383.mp4/playlist.m3u8
tags:
- SNH48
- 星梦Mini Live
- 张丹三
thumbnail: 20171003-mini-live.png
playlists:
- 全部
- 音乐
- 星梦Mini Live
- 其它
