title: 20171029 Team HⅡ 美丽世界 38
datetime: 2017-10-29T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/378
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171029/59e6c54b0cf23fa04ee4c301.mp4/playlist.m3u8
tags:
- SNH48
- 美丽世界
thumbnail: 20171029-美丽世界-38.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
