title: 20171007 Team NⅡ 以爱之名 01
datetime: 2017-10-07T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/348
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171007/59cdd9b20cf23bc6a650c14d.mp4/playlist.m3u8
tags:
- SNH48
- 以爱之名
thumbnail: 20171007-以爱之名-01.png
playlists:
- 全部
- 全部公演
- Team NⅡ
- Team NⅡ — 以爱之名
