title: 20171020 星梦Mini Live（孙歆文）
datetime: 2017-10-20T17:25:00+08:00
vod: http://live.snh48.com/Index/invedio/id/363
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171020/59e473830cf294bc616de920.mp4/playlist.m3u8
tags:
- SNH48
- 星梦Mini Live
- 孙歆文
thumbnail: 20171020-mini-live-png
playlists:
- 全部
- 音乐
- 星梦Mini Live
- 其它
