title: 20180113 Team X 命运的X号 06
datetime: 2018-01-13T19:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/459
tags:
- SNH48
- 命运的X号
- Team X
thumbnail: 20180113-命运的X号-06.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 命运的X号
