title: 20180117 Team X 命运的X号 07
datetime: 2018-01-17T19:30:00+08:00
vod: http://live.snh48.com/Index/invedio/id/464
tags:
- SNH48
- 命运的X号
- Team X
thumbnail: 20180117-命运的X号-07.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 命运的X号
