title: 20180302 Team XⅡ 代号XⅡ 63 结业特别公演暨元宵主题公演
datetime: 2018-03-02T19:30:00+08:00
vod: http://live.snh48.com/Index/invedio/id/490
m3u8: http://ts.snh48.com/chaoqing/9999/20180302173724-playlist.m3u8?endTime=20180302225800
tags:
- SNH48
- 代号XⅡ
- Team XⅡ
- XⅡ
- Team XII
- XII
thumbnail: 20180302-代号XⅡ-63.png
playlists:
- 全部
- 全部公演
- 特别公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
