title: 20180110 Team HⅡ 美丽世界 48
datetime: 2018-01-10T19:30:00+08:00
vod: http://live.snh48.com/Index/invedio/id/455
tags:
- SNH48
- 美丽世界
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20180110-美丽世界-48.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
