title: 20180112 星梦Mini Live（张昕）
datetime: 2018-01-12T17:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/457
tags:
- SNH48
- 星梦Mini Live
- 张昕
thumbnail: 20181112-mini-live.png
playlists:
- 全部
- 音乐
- 星梦Mini Live
- 其它
