title: 20180114 Team XⅡ 代号XⅡ 59 张文静生日
datetime: 2018-01-14T19:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/462
tags:
- SNH48
- 代号XⅡ
- Team XⅡ
- XⅡ
- Team XII
- XII
thumbnail: 20180114-代号XⅡ-59.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
