title: 20180120 Team XⅡ 代号XⅡ 60 陈韫凌生日
datetime: 2018-01-20T13:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/468
tags:
- SNH48
- 代号XⅡ
- Team XⅡ
- XⅡ
- Team XII
- XII
thumbnail: 20180120-代号XⅡ-60.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
