title: 20180112 Team HⅡ 美丽世界 49 星梦剧院年度MVP发表
datetime: 2018-01-12T19:30:00+08:00
tags:
- SNH48
- 美丽世界
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20180112-美丽世界-49.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
