title: 20180304 Team X 命运的X号 10
datetime: 2018-03-04T19:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/494
tags:
- SNH48
- 命运的X号
- Team X
thumbnail: 20180304-命运的X号-10.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 命运的X号
