title: 20180118 Team HⅡ “Thank You”特别主题公演
datetime: 2018-01-18T19:30:00+08:00
vod: http://live.snh48.com/Index/invedio/id/465
tags:
- SNH48
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20180118-thank-you.png
playlists:
- 全部
- 全部公演
- 特别公演
- Team HⅡ
