title: 20180104 Team XⅡ 代号XⅡ 57
datetime: 2018-01-04T19:30:00+08:00
vod: http://live.snh48.com/Index/invedio/id/448
tags:
- SNH48
- 代号XⅡ
- Team XⅡ
- XⅡ
- Team XII
- XII
thumbnail: 20180104-代号XⅡ-57.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
