title: 20180304 Team NⅡ 江真仪生日暨忆往昔特别公演
datetime: 2018-03-04T14:05:00+08:00
vod: http://live.snh48.com/Index/invedio/id/492
tags:
- SNH48
- Team NⅡ
- NⅡ
- Team NII
- NII
thumbnail: 20180304-n2.png
playlists:
- 全部
- 全部公演
- 特别公演
- Team NⅡ
