title: 20180126 星梦Mini Live（江真仪）
datetime: 2018-01-26T17:30:00+08:00
vod: http://live.snh48.com/Index/invedio/id/476
m3u8: http://ts.snh48.com/chaoqing/9999/20180126173305-playlist.m3u8
tags:
- SNH48
- 星梦Mini Live
- 江真仪
thumbnail: 20181119-mini-live.png
playlists:
- 全部
- 音乐
- 星梦Mini Live
- 其它
