title: 20180127 Team XⅡ 代号XⅡ 62 洪珮雲生日
datetime: 2018-01-27T14:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/478
tags:
- SNH48
- 代号XⅡ
- Team XⅡ
- XⅡ
- Team XII
- XII
thumbnail: 20180127-代号XⅡ-62.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
