title: 20180126 Team SⅡ 第48区 26
datetime: 2018-01-26T19:30:00+08:00
tags:
- SNH48
- 第48区
- Team SⅡ
- SⅡ
- Team SII
- SII
thumbnail: 20180126-第48区-26.png
playlists:
- 全部
- 全部公演
- Team SⅡ
- Team SⅡ — 第48区
