title: 20180125 Team XⅡ 代号XⅡ 61
datetime: 2018-01-25T19:35:00+08:00
vod: http://live.snh48.com/Index/invedio/id/475
tags:
- SNH48
- 代号XⅡ
- Team XⅡ
- XⅡ
- Team XII
- XII
thumbnail: 20180125-代号XⅡ-61.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
