title: 20180303 Team SⅡ 第48区 28
datetime: 2018-03-03T19:00:00+08:00
tags:
- SNH48
- 第48区
- Team SⅡ
- SⅡ
- Team SII
- SII
thumbnail: 20180303-第48区-28.png
playlists:
- 全部
- 全部公演
- Team SⅡ
- Team SⅡ — 第48区
