title: 20180120 Team HⅡ 美丽世界 49 刘佩鑫生日
datetime: 2018-01-20T19:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/470
tags:
- SNH48
- 美丽世界
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20180120-美丽世界-49.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
