title: 20180121 Team SⅡ 第48区 25
datetime: 2018-01-21T19:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/473
tags:
- SNH48
- 第48区
- Team SⅡ
- SⅡ
- Team SII
- SII
thumbnail: 20180121-第48区-25.png
playlists:
- 全部
- 全部公演
- Team SⅡ
- Team SⅡ — 第48区
