title: 20180119 星梦Mini Live（袁一琦）
datetime: 2018-01-19T17:25:00+08:00
vod: http://live.snh48.com/Index/invedio/id/466
m3u8: http://ts.snh48.com/chaoqing/9999/20180119165441-playlist.m3u8
tags:
- SNH48
- 星梦Mini Live
- 袁一琦
thumbnail: 20181119-mini-live.png
playlists:
- 全部
- 音乐
- 星梦Mini Live
- 其它
