title: 20180121 Team NⅡ 以爱之名 16 陆婷生日
datetime: 2018-01-21T14:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/471
tags:
- SNH48
- 以爱之名
- Team NⅡ
- NⅡ
- Team NII
- NII
thumbnail: 20180121-以爱之名-16.png
playlists:
- 全部
- 全部公演
- Team NⅡ
- Team NⅡ — 以爱之名
