title: 20180107 Team NⅡ 以爱之名 14 刘菊子生日
datetime: 2018-01-07T19:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/453
tags:
- SNH48
- 以爱之名
- Team NⅡ
- NⅡ
- Team NII
- NII
thumbnail: 20180107-以爱之名-14.png
playlists:
- 全部
- 全部公演
- Team NⅡ
- Team NⅡ — 以爱之名
