title: 20180128 Team HⅡ 美丽世界 50 徐晗生日
datetime: 2018-01-28T14:20:00+08:00
vod: http://live.snh48.com/Index/invedio/id/479
tags:
- SNH48
- 美丽世界
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20180128-美丽世界-50.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
