title: 20180301 Team SⅡ 第48区 27 迎新特别公演
datetime: 2018-03-01T19:30:00+08:00
vod: http://live.snh48.com/Index/invedio/id/488
tags:
- SNH48
- 第48区
- Team SⅡ
- SⅡ
- Team SII
- SII
thumbnail: 20180301-第48区-27.png
playlists:
- 全部
- 全部公演
- 特别公演
- Team SⅡ
- Team SⅡ — 第48区
