title: 20180111 Team XⅡ 代号XⅡ 58
datetime: 2018-01-11T19:30:00+08:00
vod: http://live.snh48.com/Index/invedio/id/456
tags:
- SNH48
- 代号XⅡ
- Team XⅡ
- XⅡ
- Team XII
- XII
thumbnail: 20180111-代号XⅡ-58.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
