title: 20171118 SNH48 Group第三届年度风尚大赏 后台综艺直播间
datetime: 2017-11-18T19:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/403
tags:
- SNH48
- BEJ48
- GNZ48
- SHY48
- CKG48
- 风尚大赏
thumbnail: 20171118-风尚后台.png
playlists:
- 全部
- 其它
