title: 20171126 Team NⅡ 以爱之名 09
datetime: 2017-11-26T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/414
tags:
- SNH48
- 以爱之名
- Team NⅡ
- NⅡ
- Team NII
- NII
thumbnail: 20171126-以爱之名-09.png
playlists:
- 全部
- 全部公演
- Team NⅡ
- Team NⅡ — 以爱之名
