title: 20170823 Team XⅡ 代号XⅡ 39
datetime: 2017-08-23T19:15:00+08:00
vod: http://live.snh48.com/Index/invedio/id/295
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20170823/5992c52b0cf28bcb9b989e5a.mp4/playlist.m3u8
tags:
- SNH48
- 代号XⅡ
thumbnail: 20170823-代号XⅡ-39.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
