title: 20171215 Team X 命运的X号 01
datetime: 2017-12-15T19:30:00+08:00
vod: http://live.snh48.com/Index/invedio/id/433
tags:
- SNH48
- 命运的X号
- Team X
thumbnail: 20171215-命运的X号-01.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 命运的X号
