title: 20171214 Team SⅡ 第48区 24
datetime: 2017-12-14T19:30:00+08:00
vod: http://live.snh48.com/Index/invedio/id/431
tags:
- SNH48
- 第48区
- Team SⅡ
- SⅡ
- Team SII
- SII
thumbnail: 20171214-第48区-24.png
playlists:
- 全部
- 全部公演
- Team SⅡ
- Team SⅡ — 第48区
