title: 20170910 Team NⅡ 专属派对 51 剧场四周年特别公演
datetime: 2017-09-10T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/314
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20170910/59a5228a0cf2abe871c6ab6a.mp4/playlist.m3u8
tags:
- SNH48
- 专属派对
thumbnail: 20170910-专属派对-51.png
playlists:
- 全部
- 全部公演
- Team NⅡ
- Team NⅡ — 专属派对
- 特别公演
