title: 20171207 Team XⅡ 代号XⅡ 55
datetime: 2017-12-07T19:15:00+08:00
vod: http://live.snh48.com/Index/invedio/id/424
tags:
- SNH48
- 代号XⅡ
- Team XⅡ
- XⅡ
- Team XII
- XII
thumbnail: 20171207-代号XⅡ-55.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
