title: 20171203 Team HⅡ 美丽世界 43
datetime: 2017-12-03T14:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/421
tags:
- SNH48
- 美丽世界
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20171203-美丽世界-43.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
