title: 20171115 Team NⅡ N队成立四周年特别公演
datetime: 2017-11-15T19:15:00+08:00
vod: http://live.snh48.com/Index/invedio/id/400
tags:
- SNH48
- Team NⅡ
- NⅡ
- Team NII
- NII
thumbnail: 20171115-n2.png
playlists:
- 全部
- 全部公演
- Team NⅡ
- 特别公演
