title: 20171224 Team X 命运的X号 04 孙歆文生日
datetime: 2017-12-24T14:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/442
tags:
- SNH48
- 命运的X号
- Team X
thumbnail: 20171224-命运的X号-04.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 命运的X号
