title: 20171006 星梦Mini Live（袁航）
datetime: 2017-10-06T11:55:00+08:00
vod: http://live.snh48.com/Index/invedio/id/345
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171006/59cc81a30cf25ea09bb3d385.mp4/playlist.m3u8
tags:
- SNH48
- 星梦Mini Live
- 袁航
thumbnail: 20171006-mini-live.png
playlists:
- 全部
- 音乐
- 星梦Mini Live
- 其它
