title: 20171018 Team X 梦想的旗帜 58
datetime: 2017-10-18T19:15:00+08:00
vod: http://live.snh48.com/Index/invedio/id/361
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171018/59dda0ac0cf2d32740bafa68.mp4/playlist.m3u8
tags:
- SNH48
- 梦想的旗帜
thumbnail: 20171018-梦想的旗帜-58.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 梦想的旗帜
