title: 20171221 Team NⅡ 以爱之名 12
datetime: 2017-12-21T19:30:00+08:00
vod: http://live.snh48.com/Index/invedio/id/440
tags:
- SNH48
- 以爱之名
- Team NⅡ
- NⅡ
- Team NII
- NII
thumbnail: 20171221-以爱之名-12.png
playlists:
- 全部
- 全部公演
- Team NⅡ
- Team NⅡ — 以爱之名
