title: 20171130 Team XⅡ 代号XⅡ 54
datetime: 2017-11-30T19:30:00+08:00
vod: http://live.snh48.com/Index/invedio/id/416
tags:
- SNH48
- 代号XⅡ
- Team XⅡ
- XⅡ
- Team XII
- XII
thumbnail: 20171130-代号XⅡ-54.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
