title: 20171210 Team XⅡ 代号XⅡ 56 徐诗琪生日
datetime: 2017-12-10T14:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/427
tags:
- SNH48
- 代号XⅡ
- Team XⅡ
- XⅡ
- Team XII
- XII
thumbnail: 20171210-代号XⅡ-56.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
