title: 20171124 星梦Mini Live（祁静）
datetime: 2017-11-24T17:25:00+08:00
vod: http://live.snh48.com/Index/invedio/id/408
tags:
- SNH48
- 星梦Mini Live
- 祁静
thumbnail: 20171124-mini-live.png
playlists:
- 全部
- 音乐
- 星梦Mini Live
- 其它
