title: 20171201 星梦Mini Live（许逸）
datetime: 2017-12-01T17:50:00+08:00
vod: http://live.snh48.com/Index/invedio/id/417
tags:
- SNH48
- 星梦Mini Live
- 许逸
thumbnail: 20171201-mini-live.png
playlists:
- 全部
- 音乐
- 星梦Mini Live
- 其它
