title: 20171122 Team X 梦想的旗帜 65
datetime: 2017-11-22T19:30:00+08:00
vod: http://live.snh48.com/Index/invedio/id/406
tags:
- SNH48
- 梦想的旗帜
- Team X
thumbnail: 20171122-梦想的旗帜-65.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 梦想的旗帜
