title: 20170916 Team NⅡ 专属派对 51 千秋乐
datetime: 2017-09-16T13:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/319
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20170916/59ae59b00cf2900f3d526a3d.mp4/playlist.m3u8
tags:
- SNH48
- 专属派对
thumbnail: 20170916-专属派对-52.png
playlists:
- 全部
- 全部公演
- Team NⅡ
- Team NⅡ — 专属派对
