title: 20171216 Team X 命运的X号 02
datetime: 2017-12-16T19:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/434
tags:
- SNH48
- 命运的X号
- Team X
thumbnail: 20171216-命运的X号-02.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 命运的X号
