title: 20171201 Team SⅡ 第48区 22 重庆巡演
datetime: 2017-12-01T19:15:00+08:00
vod: http://live.ckg48.com/Index/invedio/id/385
tags:
- SNH48
- 第48区
- Team SⅡ
- SⅡ
- Team SII
- SII
thumbnail: 20171201-第48区-22.png
playlists:
- 全部
- 全部公演
- Team SⅡ
- Team SⅡ — 第48区
