title: 20171012 Team X 梦想的旗帜 56
datetime: 2017-10-12T19:15:00+08:00
vod: http://live.snh48.com/Index/invedio/id/352
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171012/59dae22f0cf2085d7b3feafe.mp4/playlist.m3u8
tags:
- SNH48
- 梦想的旗帜
thumbnail: 20171012-梦想的旗帜-56.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 梦想的旗帜
