title: 20171208 星梦Mini Live（李宇琪）
datetime: 2017-12-08T17:25:00+08:00
vod: http://live.snh48.com/Index/invedio/id/425
m3u8: http://ts.snh48.com/chaoqing/9999/20171208170730-playlist.m3u8?beginTime=20171208172500
tags:
- SNH48
- 星梦Mini Live
- 李宇琪
thumbnail: 20171208-mini-live.png
playlists:
- 全部
- 音乐
- 星梦Mini Live
- 其它
