title: 20171108 Team XⅡ 代号XⅡ 52
datetime: 2017-11-08T19:15:00+08:00
vod: http://live.snh48.com/Index/invedio/id/391
tags:
- SNH48
- 代号XⅡ
thumbnail: 20171108-代号XⅡ-52.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
