title: 20170908 Team HⅡ 剧场四周年特别公演
datetime: 2017-09-08T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/312
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20170908/59a521860cf2abe871c6ab68.mp4/playlist.m3u8
tags:
- SNH48
- 美丽世界
thumbnail: 20170908-美丽世界-31.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
- 特别公演
