title: 20171201 Team X 梦想的旗帜 67
datetime: 2017-12-01T19:15:00+08:00
vod: http://live.snh48.com/Index/invedio/id/418
tags:
- SNH48
- 梦想的旗帜
- Team X
thumbnail: 20171201-梦想的旗帜-67.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 梦想的旗帜
