title: 20171209 Team X 梦想的旗帜 69 千秋乐
datetime: 2017-12-09T13:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/426
tags:
- SNH48
- 梦想的旗帜
- Team X
thumbnail: 20171209-梦想的旗帜-69.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 梦想的旗帜
