title: 20171215 星梦Mini Live（袁雨桢）
datetime: 2017-12-15T17:25:00+08:00
vod: http://live.snh48.com/Index/invedio/id/432
tags:
- SNH48
- 星梦Mini Live
- 袁雨桢
thumbnail: 20171215-mini-live.png
playlists:
- 全部
- 音乐
- 星梦Mini Live
- 其它
