title: 20170902 Team HⅡ 美丽世界 29
datetime: 2017-09-02T13:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/304
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20170902/599bd1690cf25ef21dd911ed.mp4/playlist.m3u8
tags:
- SNH48
- 美丽世界
thumbnail: 20170902-美丽世界-29.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
