title: 20171222 7SENSES 广州巡演
datetime: 2017-12-22T19:20:00+08:00
vod: http://live.gnz48.com/Index/invedio/id/264
tags:
- SNH48
- 7SENSES
- 戴萌
- 孔肖吟
- 许佳琪
- 张语格
- 赵粤
- 许杨玉琢
- 陈琳
thumbnail: 20171222-7senses.png
playlists:
- 全部
- 全部公演
- 特别公演
- 7SENSES
