title: 20171021 Team HⅡ 美丽世界 36 吴燕文生日
datetime: 2017-10-21T13:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/365
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171021/59dda1090cf2d32740bafa6b.mp4/playlist.m3u8
tags:
- SNH48
- 美丽世界
thumbnail: 20171021-美丽世界-36.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
