title: 20171210 Team NⅡ 以爱之名 11
datetime: 2017-12-10T19:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/429
tags:
- SNH48
- 以爱之名
- Team NⅡ
- NⅡ
- Team NII
- NII
thumbnail: 20171210-以爱之名-11.png
playlists:
- 全部
- 全部公演
- Team NⅡ
- Team NⅡ — 以爱之名
