title: 20171220 Team HⅡ 美丽世界 45
datetime: 2017-12-20T19:15:00+08:00
vod: http://live.snh48.com/Index/invedio/id/439
tags:
- SNH48
- 美丽世界
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20171220-美丽世界-45.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
