title: 20171004 星梦Mini Live中秋古风专场（陈思、徐晗、严佼君）
datetime: 2017-10-04T14:50:00+08:00
vod: http://live.snh48.com/Index/invedio/id/342
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171004/59cc814d0cf25ea09bb3d384.mp4/playlist.m3u8
tags:
- SNH48
- 星梦Mini Live
- 陈思
- 徐晗
- 严佼君
thumbnail: 20171004-mini-live.png
playlists:
- 全部
- 音乐
- 星梦Mini Live
- 其它
