title: 20171110 Team HⅡ 美丽世界 39
datetime: 2017-11-10T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/393
tags:
- SNH48
- 美丽世界
thumbnail: 20171110-美丽世界-40.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
