title: 20171014 Team X 梦想的旗帜 57
datetime: 2017-10-14T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/357
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171014/59dae28c0cf2085d7b3feb01.mp4/playlist.m3u8
tags:
- SNH48
- 梦想的旗帜
thumbnail: 20171014-梦想的旗帜-57.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 梦想的旗帜
