title: 20171125 Team NⅡ 以爱之名 08 万丽娜生日
datetime: 2017-11-25T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/412
tags:
- SNH48
- 以爱之名
- Team NⅡ
- NⅡ
- Team NII
- NII
thumbnail: 20171125-以爱之名-08.png
playlists:
- 全部
- 全部公演
- Team NⅡ
- Team NⅡ — 以爱之名
