title: 20171129 Team HⅡ 美丽世界 42
datetime: 2017-11-29T19:15:00+08:00
vod:
tags:
- SNH48
- 美丽世界
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20171129-美丽世界-42.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
