title: 20170906 Team XⅡ 剧场四周年特别公演
datetime: 2017-09-06T19:15:00+08:00
vod: http://live.snh48.com/Index/invedio/id/309
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20170906/59a51ff30cf2abe871c6ab66.mp4/playlist.m3u8
tags:
- SNH48
- 代号XⅡ
thumbnail: 20170906-代号XⅡ-43.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
- 特别公演
