title: 20171124 Team SⅡ 第48区 21 星梦学院主题公演
datetime: 2017-11-24T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/409
tags:
- SNH48
- 第48区
- Team SⅡ
- SⅡ
- Team SII
- SII
thumbnail: 20171124-第48区-21.png
playlists:
- 全部
- 全部公演
- Team SⅡ
- Team SⅡ — 第48区
