title: 20171207 7SENSES 北京巡演
datetime: 2017-12-07T19:15:00+08:00
vod: http://live.bej48.com/Index/invedio/id/270
tags:
- SNH48
- 7SENSES
- 戴萌
- 孔肖吟
- 许佳琪
- 张语格
- 赵粤
- 许杨玉琢
- 陈琳
thumbnail: 20171207-7senses.png
playlists:
- 全部
- 全部公演
- 特别公演
- 7SENSES
