title: 20171116 Team X 梦想的旗帜 64
datetime: 2017-11-16T19:40:00+08:00
vod: http://live.snh48.com/Index/invedio/id/401
tags:
- SNH48
- 梦想的旗帜
thumbnail: 20171116-梦想的旗帜-64.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 梦想的旗帜
