title: 20171217 7SENSES 上海巡演
datetime: 2017-12-17T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/436
tags:
- SNH48
- 7SENSES
- 戴萌
- 孔肖吟
- 许佳琪
- 张语格
- 赵粤
- 许杨玉琢
- 陈琳
thumbnail: 20171217-7senses.png
playlists:
- 全部
- 全部公演
- 特别公演
- 7SENSES
