title: 20171112 Team HⅡ 美丽世界 40 郝婉晴生日
datetime: 2017-11-12T13:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/397
tags:
- SNH48
- 美丽世界
thumbnail: 20171112-美丽世界-40.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
