title: 20171123 Team HⅡ 美丽世界 41
datetime: 2017-11-23T19:15:00+08:00
vod: http://live.snh48.com/Index/invedio/id/407
tags:
- SNH48
- 美丽世界
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20171123-美丽世界-41.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
