title: 20171013 Team XⅡ 代号XⅡ 49
datetime: 2017-10-13T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/354
m3u8: http://ts.snh48.com/vod/z1.chaoqing.9999/20171013/59dae24b0cf2085d7b3feaff.mp4/playlist.m3u8
tags:
- SNH48
- 代号XⅡ
thumbnail: 20171013-代号XⅡ-49.png
playlists:
- 全部
- 全部公演
- Team XⅡ
- Team XⅡ — 代号XⅡ
