title: 20171203 Team X 梦想的旗帜 68 B50中报
datetime: 2017-12-03T19:00:00+08:00
vod: http://live.snh48.com/Index/invedio/id/422
tags:
- SNH48
- 梦想的旗帜
- Team X
thumbnail: 20171203-梦想的旗帜-68.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 梦想的旗帜
