title: 20171202 Team SⅡ 第48区 23 重庆巡演
datetime: 2017-12-02T14:00:00+08:00
vod: http://live.ckg48.com/Index/invedio/id/386
tags:
- SNH48
- 第48区
- Team SⅡ
- SⅡ
- Team SII
- SII
thumbnail: 20171202-第48区-23.png
playlists:
- 全部
- 全部公演
- Team SⅡ
- Team SⅡ — 第48区
