title: 20171126 Team X 梦想的旗帜 66
datetime: 2017-11-26T13:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/413
tags:
- SNH48
- 梦想的旗帜
- Team X
thumbnail: 20171126-梦想的旗帜-66.png
playlists:
- 全部
- 全部公演
- Team X
- Team X — 梦想的旗帜
