title: 20180101 Team HⅡ 美丽世界 46
datetime: 2018-01-01T18:45:00+08:00
vod: http://live.snh48.com/Index/invedio/id/447
tags:
- SNH48
- 美丽世界
- Team HⅡ
- HⅡ
- Team HII
- HII
thumbnail: 20180101-美丽世界-46.png
playlists:
- 全部
- 全部公演
- Team HⅡ
- Team HⅡ — 美丽世界
